---
paks:
  - name: org.libreoffice.LibreOffice
  - name: org.glimpse_editor.Glimpse
  - name: com.discordapp.Discord
  - name: org.freecadweb.FreeCAD
  - name: us.zoom.Zoom
  - name: com.github.libresprite.LibreSprite
  - name: com.github.wwmm.pulseeffects
  - name: io.dbeaver.DBeaverCommunity
  - name: org.chromium.Chromium
  - name: com.vscodium.codium
