---
packages:
  # ui
  - light-locker
  # general
  - curl
  - pkgfile
  - unclutter
  - wget
  - yamllint
  - yay
  # Dev
  ## haskell
  - ghc
  - ghc-libs
  - stack
  ## terminal
  - alacritty
  - entr # watch files and re-run command
  - figlet # make large banners out of ascii
  - kitty
  - neovim
  - task # taskwarrior
  - timew # timewarrior
  - taskell
  ## automation
  - ansible
  - ansible-lint
  - packer
  - terraform
  - vault
  ## clojure dev
  - clojure
  - leiningen
  ## node dev
  - nodejs
  - npm

aur:
  # ui
  - lightdm-mini-greeter
  # general
  - luarocks
  # DB tools
  - robo3t-bin # mongodb UI tool
  # terminal
  - bat # like cat but rusty
  - zoxide # warp around cd rustily
  - taskwarrior-tui # taskwarrior tui built in rust
  - toilet # asci out text
  - dust # rust based disk usage utility
  - tealdeer # TL;DR for deers (rusty)
  - navi # interactive CL tool for cheats (sorta like TLDR)
  - procs # rusty processes
  - wakatime-cli-bin # new go version
  # automation
  - terraform-lsp-git
  - yamllint
  # clojure dev
  - babashka-bin # cli clj runner for faster tools
  - boot
  - clojure-lsp-bin
  - clj-kondo-bin
  - fennel
  - joker-bin
